#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_mit_LINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="kontakte")]
	public partial class KontakteDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKontakte(Kontakte instance);
    partial void UpdateKontakte(Kontakte instance);
    partial void DeleteKontakte(Kontakte instance);
    #endregion
		
		public KontakteDataContext() : 
				base(global::SQL_mit_LINQ.Properties.Settings.Default.kontakteConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KontakteDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KontakteDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KontakteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KontakteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Kontakte> Kontakte
		{
			get
			{
				return this.GetTable<Kontakte>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kontakte")]
	public partial class Kontakte : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kNummer;
		
		private string _nachname;
		
		private string _vorname;
		
		private string _strasse;
		
		private string _postleitzahl;
		
		private string _ort;
		
		private string _telefon;
		
		private string _email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkNummerChanging(int value);
    partial void OnkNummerChanged();
    partial void OnnachnameChanging(string value);
    partial void OnnachnameChanged();
    partial void OnvornameChanging(string value);
    partial void OnvornameChanged();
    partial void OnstrasseChanging(string value);
    partial void OnstrasseChanged();
    partial void OnpostleitzahlChanging(string value);
    partial void OnpostleitzahlChanged();
    partial void OnortChanging(string value);
    partial void OnortChanged();
    partial void OntelefonChanging(string value);
    partial void OntelefonChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public Kontakte()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kNummer", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kNummer
		{
			get
			{
				return this._kNummer;
			}
			set
			{
				if ((this._kNummer != value))
				{
					this.OnkNummerChanging(value);
					this.SendPropertyChanging();
					this._kNummer = value;
					this.SendPropertyChanged("kNummer");
					this.OnkNummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nachname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nachname
		{
			get
			{
				return this._nachname;
			}
			set
			{
				if ((this._nachname != value))
				{
					this.OnnachnameChanging(value);
					this.SendPropertyChanging();
					this._nachname = value;
					this.SendPropertyChanged("nachname");
					this.OnnachnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vorname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string vorname
		{
			get
			{
				return this._vorname;
			}
			set
			{
				if ((this._vorname != value))
				{
					this.OnvornameChanging(value);
					this.SendPropertyChanging();
					this._vorname = value;
					this.SendPropertyChanged("vorname");
					this.OnvornameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strasse", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string strasse
		{
			get
			{
				return this._strasse;
			}
			set
			{
				if ((this._strasse != value))
				{
					this.OnstrasseChanging(value);
					this.SendPropertyChanging();
					this._strasse = value;
					this.SendPropertyChanged("strasse");
					this.OnstrasseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postleitzahl", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string postleitzahl
		{
			get
			{
				return this._postleitzahl;
			}
			set
			{
				if ((this._postleitzahl != value))
				{
					this.OnpostleitzahlChanging(value);
					this.SendPropertyChanging();
					this._postleitzahl = value;
					this.SendPropertyChanged("postleitzahl");
					this.OnpostleitzahlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ort", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ort
		{
			get
			{
				return this._ort;
			}
			set
			{
				if ((this._ort != value))
				{
					this.OnortChanging(value);
					this.SendPropertyChanging();
					this._ort = value;
					this.SendPropertyChanged("ort");
					this.OnortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="NVarChar(20)")]
		public string telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this.OntelefonChanging(value);
					this.SendPropertyChanging();
					this._telefon = value;
					this.SendPropertyChanged("telefon");
					this.OntelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(30)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
