<?xml version="1.0" encoding="utf-8"?><Database Name="kontakte" Class="KontakteDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\kontakte.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="SQL_mit_LINQ.Properties.Settings" SettingsPropertyName="kontakteConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Kontakte" Member="Kontaktes">
    <Type Name="Kontakte">
      <Column Name="kNummer" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nachname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="vorname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="strasse" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="postleitzahl" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ort" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telefon" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
</Database>